FROM 853695319/ssh-python-key:v1

LABEL Name=scrapy Version=0.0.1

WORKDIR /app
COPY ./requirements.txt /app

# Using pip
# RUN python3 -m pip install -r requirements.txt

# Using pipenv:
# locking 过程比较久，更换国内源
RUN python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ pipenv \
    && pipenv --pypi-mirror https://pypi.tuna.tsinghua.edu.cn/simple/ install -r requirements.txt

COPY . /app

# SSH守护进程端口
EXPOSE 22

RUN chmod +x /app/run.sh
# 不能用 pipenv shell 因为这个是在后台运行的
CMD ["bash", "/app/run.sh"]